config/routes.rb
Rails.application.routes.draw do
  resources :machines
  root to: 'machines#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/machine.rb
class Machine < ApplicationRecord
  scope :ip_search, ->(q) { where("text(ip) ILIKE '%#{q}%'") }

  def self.ransackable_scopes(_auth_object = nil)
    [:ip_search]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :set_machine, only: %i[show edit update destroy]

  # GET /machines or /machines.json
  def index
    @q = Machine.ransack(params[:q])
    @machines = @q.result(distinct: true)
  end

  # GET /machines/1 or /machines/1.json
  def show; end

  # GET /machines/new
  def new
    @machine = Machine.new
  end

  # GET /machines/1/edit
  def edit; end

  # POST /machines or /machines.json
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /machines/1 or /machines/1.json
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1 or /machines/1.json
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_machine
    @machine = Machine.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def machine_params
    params.require(:machine).permit(:name, :ip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RansackedEp3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/machines/_form.html.erb
<%= form_with(model: machine) do |form| %>
  <% if machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
        <% machine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/machines/_search_form.html.erb
<%= search_form_for @q do |f| %>

    <%= f.label :name_cont %>
    <%= f.search_field :name_cont %>

    <%= f.label :ip_eq %>
    <%= f.search_field :ip_search %>

    <%= f.submit %>
<% end %>

app/views/machines/edit.html.erb
<h1>Editing Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

app/views/machines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Machines</h1>
<%= render 'machines/search_form' %>
<table>
  <thead>
    <tr>
      <th><%= sort_link(@q, :name, "Name", default_order: :asc) %></th>
      <th><%= sort_link(@q, :ip, "IP Address") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= machine.name %></td>
        <td><%= machine.ip %></td>
        <td><%= link_to 'Show', machine %></td>
        <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
        <td><%= link_to 'Destroy', machine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Machine', new_machine_path %>

app/views/machines/new.html.erb
<h1>New Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Back', machines_path %>

app/views/machines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @machine.name %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @machine.ip %>
</p>

<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>